
##### 도서 쇼핑몰 프로젝트 테이블 생성 SQL #####

### 생성 예상 테이블 ###
#1. 회원 정보 테이블 SHOP_MEMBER
#2. 도서 카테고리 테이블 BOOK_CATEGORY
#3. 도서 정보 테이블 SHOP_BOOK
#4. 장바구니 테이블 SHOP_CART
#5. 구매 정보 테이블 SHOP_BUY

#회원정보 테이블 생성문

CREATE TABLE SHOP_MEMBER (
	MEM_EMAIL VARCHAR(50) PRIMARY KEY
	, MEM_PW VARCHAR(50) NOT NULL
	, MEM_NAME VARCHAR(30) NOT NULL
	, MEM_TEL VARCHAR(15) NOT NULL UNIQUE #'010-1111-2222'
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(100)
	, IS_USING VARCHAR(10) DEFAULT 'Y'  #'Y' : 사용중, 'N' : 사용 안 함
	, MEM_ROLE VARCHAR(20) DEFAULT 'USER'  #USER : 회원, MANAGER : 쇼핑몰 운영자, ADMIN : 관리자
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

UPDATE SHOP_MEMBER
SET
	MEM_EMAIL = 'manager'
	, MEM_PW = '1111'
	, MEM_ROLE = 'MANAGER'
WHERE MEM_EMAIL = 'qoreogns3';

SELECT * FROM SHOP_MEMBER;

# 가장 최근 등록한 멤버 삭제 쿼리
DELETE FROM SHOP_MEMBER 
WHERE JOIN_DATE = (SELECT MAX(JOIN_DATE) FROM SHOP_MEMBER);

# 도서 카테고리 정보
CREATE TABLE BOOK_CATEGORY(
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE
)

# 카테고리 기본 데이터 INSERT
INSERT INTO BOOK_CATEGORY VALUES (1, 'IT/인터넷');
INSERT INTO BOOK_CATEGORY VALUES (2, '자기계발');
INSERT INTO BOOK_CATEGORY VALUES (3, '소설/에세이');

SELECT * FROM BOOK_CATEGORY;

# 도서 정보 테이블
CREATE TABLE SHOP_BOOK (
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_TITLE VARCHAR(30) NOT NULL
	, AUTHOR VARCHAR(20) NOT NULL 
	, BOOK_PRICE INT NOT NULL
	, BOOK_STOCK INT DEFAULT 10
	, BOOK_INTRO VARCHAR(50)
	, PUBLISH_DATE DATETIME #출판일
	, CATE_NUM INT NOT NULL REFERENCES BOOK_CATEGORY (CATE_NUM)
);

SELECT * FROM SHOP_BOOK;

UPDATE SHOP_BOOK
SET BOOK_TITLE = '빨리 만나는 자바'
WHERE BOOK_NUM = 8;